
package employeemgmt.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceImplementation", targetNamespace = "http://services.employeemgmt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceImplementation {


    /**
     * 
     * @param arg0
     * @return
     *     returns employeemgmt.services.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://services.employeemgmt/", className = "employeemgmt.services.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://services.employeemgmt/", className = "employeemgmt.services.GetEmployeeByIdResponse")
    @Action(input = "http://services.employeemgmt/EmployeeServiceImplementation/getEmployeeByIdRequest", output = "http://services.employeemgmt/EmployeeServiceImplementation/getEmployeeByIdResponse")
    public Employee getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
