
package employeemgmt.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeServiceImplementationService", targetNamespace = "http://services.employeemgmt/", wsdlLocation = "http://localhost:9000/any/name?wsdl")
public class EmployeeServiceImplementationService
    extends Service
{

    private final static URL EMPLOYEESERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName EMPLOYEESERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://services.employeemgmt/", "EmployeeServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/any/name?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        EMPLOYEESERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public EmployeeServiceImplementationService() {
        super(__getWsdlLocation(), EMPLOYEESERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public EmployeeServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EmployeeServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public EmployeeServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EmployeeServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeServiceImplementation
     */
    @WebEndpoint(name = "EmployeeServiceImplementationPort")
    public EmployeeServiceImplementation getEmployeeServiceImplementationPort() {
        return super.getPort(new QName("http://services.employeemgmt/", "EmployeeServiceImplementationPort"), EmployeeServiceImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServiceImplementation
     */
    @WebEndpoint(name = "EmployeeServiceImplementationPort")
    public EmployeeServiceImplementation getEmployeeServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.employeemgmt/", "EmployeeServiceImplementationPort"), EmployeeServiceImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw EMPLOYEESERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return EMPLOYEESERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
